
#Common configuration settings
[common]
	#Blocks that will fall and break into items when hitting a non-solid block. Format: modid:name
	gravelBlocks = ["minecraft:gravel"]
	#If set to true, the mod will trigger when mining gravel as well, instead of only when mining a non-gravel block below gravel.
	triggerOnGravel = true
	#Blocks that are non-solid and can be destroyed in a single hit. Format: modid:name (for use on clients)
	torchItems = ["minecraft:torch"]

