
[health]
	# Colors for every 10 hearts (not counting the default red)
	# All values are written as hexadecimal RGB color in '#RRGGBB' format
	healthColors = ["#DAA520", "#00BFFF", "#8B4513", "#008000", "#800000", "#4B0082", "#FF8C00", "#C71585", "#F5F5F5", "#000080", "#708090", "#F08080"]
	# Show vanilla hearts
	healthVanilla = true
	# Two alternating colors when poisoned
	healthPoisonColors = ["#739B00", "#96CD00"]
	# Two alternating colors when withered
	healthWitherColors = ["#0F0F0F", "#2D2D2D"]

[absorption]
	# Colors for every 10 hearts (not counting the default yellow)
	# All values are written as hexadecimal RGB color in '#RRGGBB' format
	absorptionColors = ["#E1FA9B", "#A0FFAF", "#AAFFFA", "#AACDFF", "#D7B4FF", "#FAA5FF", "#FFB4B4", "#FFAA7D", "#D7F0FF", "#EBFFFA"]
	# Two alternating colors when poisoned
	# Can be empty in case of vanilla behaviour where heart background is rendered without hearts
	absorptionPoisonColors = []
	# Show vanilla hearts
	absorptionVanilla = true
	# Two alternating colors when withered
	# Can be empty in case of vanilla behaviour where heart background is rendered without hearts
	absorptionWitherColors = []

	[absorption.advanced]
		# Display mode for absorption
		# absorption.advanced.absorptionOverHealth must to be true
		# Modes: 
		#   "BEGINNING":
		#     Absorption always starts at first heart.
		#   "AFTER_HEALTH":
		#     Absorption starts after the last highest health heart and loops back to first health heart if overflowing.
		#     This means that health hearts will be hidden when absorption has 10 or more hearts.
		#       Example 1: If a player has 10 health (5 hearts), absorption will render itself in the last
		#                    five hearts and in case it is higher it will loop back over first five health hearts.
		#       Example 2: If a player has more than 20 absorption, second color is shown the same way as in "BEGINNING".
		#       Example 3: If player health is divisible by 20, absorption is shown the same way as in "BEGINNING".
		#   "AFTER_HEALTH_ADVANCED":
		#     Absorption starts after the last highest health heart and loops back to first absorption heart if overflowing.
		#     This means that no matter how much absorption there is, health hearts will almost always be visible.
		#       Example 1: If a player has 18 health (9 hearts), absorption will render itself in the last
		#                  empty heart and color itself accordingly, e.g. absorption 0 has 2 hearts and
		#                  will render using the second color as the first color is used for the first heart.
		#       Example 2: If a player has 30 health (15 hearts), absorption will render itself in the last
		#                  five hearts and color itself accordingly, e.g. absorption 2 has 6 hearts and
		#                  will render first heart using second color and rest using first color.
		#       Example 3: If player health is divisible by 20, absorption is shown the same way as in "BEGINNING".
		#   "AS_HEALTH":
		#     Absorption is rendered as health, making all colors and values same as health.
		#Allowed Values: BEGINNING, AFTER_HEALTH, AFTER_HEALTH_ADVANCED, AS_HEALTH
		absorptionOverHealthMode = "AFTER_HEALTH_ADVANCED"
		# Display absorption in the same row as health
		# Absorption is rendered after and over health depending on the mode
		absorptionOverHealth = false

