#
# Average distance between spawn attempts for Repurposed Structures Witch Huts.
# 1 for spawning in most chunks and 1001 for no spawn.
#Range: 1 ~ 1001
witchHutsOakMaxChunkDistance = 96
#Range: 1 ~ 1001
witchHutsTaigaMaxChunkDistance = 96
#Range: 1 ~ 1001
witchHutsGiantTreeTaigaMaxChunkDistance = 96
#Range: 1 ~ 1001
witchHutsBirchMaxChunkDistance = 96
#Range: 1 ~ 1001
witchHutsDarkForestMaxChunkDistance = 96

